# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
flutter_application_path = '../flutter_ui'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
target 'iOS (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS (iOS)
  install_all_flutter_pods(flutter_application_path)
end

target 'iOS (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS (macOS)
end
